directory: /data/music/music_data/beets
library: /data/music/music_var/beetslibrary.blb
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: cover
threaded: yes
ui:
  color: yes
import:
    move: yes
clutter: [ "Thumbs.DB", ".DS_Store", "cover.jpg", "cover.png" ]
format_item: '$genre :$grouping  $artist - $album - $title $path'
format_album: '$album_grouping $id $genre :$albumtype  $albumartist - $album $path'
pluginpath:
#   - /mopidy-bigbeet/beetsplug
   - /data/music/music_var/beet-config/beetsplugs/
plugins:
    alternatives
    web
    duplicates
    fetchart
    rewrite
    inline
    lastgenre
    bigbeet
    missing
    fuzzy
    info
    edit
    the

#    lyrics

chroma:
    auto: yes

lastgenre:
   auto: no
   source: artist 
   count: 1
   canonical: /data/music/music_var/beet-config/genres-tree.yaml 
   whitelist: /data/music/music_var/beet-config/genres.txt

the:
    strip: yes

per_disc_numbering: yes
asciify_paths: yes
replace:
    ', ': '-'
    '[\\/ ,]': _
    '^\.': _
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    '\.$': _
    '&': _and_
    '\s+$': ''
    '"': ''
    "'": ''
    "[!:;]": ''
    '\(.*?\)': ''
    '\[.*?\]': ''
    '__': _
    '\.\.': ''
match:
    max_rec:
        missing_tracks: low

alternatives:
  HighRes:
    directory: /data/music/music_data/alternatives/highres
    query: "bitdepth:16.."
    paths:
      default: %if{%ifdef{album_grouping},-${album_grouping},NO_GROUP}/%asciify{%if{$albumartist_sort,$albumartist_sort,$albumartist}}/%if{$original_year,${original_year}_,%if{$year,${year}-}}%asciify{$album}/%if{$disc,$disc-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
      comp: %if{%ifdef{album_grouping},-${album_grouping},NO_GROUP}/00_Compilations/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_$title}
    formats: link

item_fields:
    3digit_track: u'%03i' % (track)

paths:
    default: %if{%ifdef{album_grouping},-${album_grouping},%upper{%left{$albumartist_sort,1}}}/%asciify{%if{$albumartist_sort,$albumartist_sort,$albumartist}}/%if{$original_year,${original_year}_,%if{$year,${year}-}}%asciify{$album}/%if{$disc,$disc-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
    album:"ARD Radio Tatort": 00_HOERSPIELE/${album}/${3digit_track}_${grouping}-${year}_-_%if{${artist},${artist}_-_}${album}_-_$title
    genre:"Radio Play": 00_HOERSPIELE/%if{${grouping},${grouping},%if{${album},${album},Hoerspiel}}/%if{$original_year,${original_year}_,%if{$year,${year}-}}%asciify{%if{${artist},${artist}_-_}%if{${album},${album}_-_}$title}%if{$track,-Teil_$track}%if{$tracktotal,_von_$tracktotal}
    singleton: %if{${grouping},-${grouping}/00_Singletons,00_Singletons/-${genre}f{$albumartist_sort,$albumartist_sort,$albumartist}/%asciify{${artist}_-_$title}
    album:Fabric: -Electronica/00_Compilations/Fabric/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
    grouping:Total: -Electronica/00_Compilations/Total/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
    album:"Festive Fifty": 00_Compilations/John_Peel/Festive_Fifties/%if{$year,${year},%asciify{$album}}/%if{$track,${track}_-_}%asciify{${artist}_-_$title}
    album:"Festive Fifty All": 00_Compilations/John_Peel/Festive_Fifties/%if{$year,${year}-All_Time,%asciify{$album}}/%if{$track,${track}_-_}%asciify{${artist}_-_$title}
    album:"Punk Sessions": -Punk/00_Compilations/John_Peel/Punk_Sessions/%asciify{$artist}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
    album:"The British Invasion": -Rock//00_Compilations/The_British_Invasion/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_${album}_-_$title}
    comp: %if{%ifdef{album_grouping},-${album_grouping},-${genre}}/00_Compilations/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_$title}
    albumartist:"Various Artist": %if{%ifdef{album_grouping},-${album_grouping},-${genre}}/00_Compilations/%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{${artist}_-_$title}
    albumtype:soundtrack: 00_Soundtracks/%if{$original_year,${original_year}_}%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{%if{$artist,${artist}_-_}}%asciify{$title}
    albumtype:spokenword: 00_Spokenword/%if{$albumartist,$albumartist,$artist}/%if{$original_year,${original_year}_}%asciify{$album}/%if{$disc,${disc}-}%if{$track,${track}_-_}%asciify{$title}

rewrite:
    artist The Jimi Hendrix Experience: Jimi Hendrix
    artist Anna Yuryevna Netrebko: Anna Netrebko
    artist Anna Iurevna Netrebko: Anna Netrebko
    albumartist Anna Iurevna Netrebko: Anna Netrebko
    artist Marc Bolan and T. Rex: T. Rex
    artist Belle and Sebastian feat. The Maisonettes: Belle and Sebastian
    artist “Brother” Jack McDuff: Jack McDuff
    artist Universal Indicator: Aphex Twin (aka Universal Indicator)
    albumartist Universal Indicator: Aphex Twin
    albumartist Aphex Twin (aka Universal Indicator): Aphex Twin
    albumartist Aphex Twin (aka Polygon Window): Aphex Twin
    albumartist Aphex Twin (aka Bradley Strider): Aphex Twin
    albumartist Aphex Twin (aka AFX): Aphex Twin
    albumartist 'Lou Reed & Nico': Lou Reed
    albumartist "Lou Reed, John Cale & Nico": Lou Reed
    albumartist The Residents & Renaldo & The Loaf: The Residents
 
